# Generated by Django 5.1.7 on 2025-03-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_config', '0003_user_is_admin_alter_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
