# Generated by Django 5.1.7 on 2025-03-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_config', '0004_mockdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
